# Generated by Django 4.2.23 on 2025-06-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="SystemData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField()),
            ],
            options={
                "verbose_name": "System Data",
                "verbose_name_plural": "System Data",
                "db_table": "system_data",
            },
        ),
    ]
