# Generated by Django 4.2.23 on 2025-06-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
    ]

    operations = []
