# Generated by Django 4.2.23 on 2025-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_auto_20250612_0920"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("existing_business", "Existing Business"),
                    ("new_business", "New Business"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture"),
                    ("automotive", "Automotive"),
                    ("banking", "Banking"),
                    ("construction", "Construction"),
                    ("consulting", "Consulting"),
                    ("education", "Education"),
                    ("electronics", "Electronics"),
                    ("energy", "Energy"),
                    ("finance", "Finance"),
                    ("healthcare", "Healthcare"),
                    ("hospitality", "Hospitality"),
                    ("insurance", "Insurance"),
                    ("manufacturing", "Manufacturing"),
                    ("media", "Media"),
                    ("nonprofit", "Non-profit"),
                    ("real_estate", "Real Estate"),
                    ("retail", "Retail"),
                    ("technology", "Technology"),
                    ("telecommunications", "Telecommunications"),
                    ("transportation", "Transportation"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture"),
                    ("automotive", "Automotive"),
                    ("banking", "Banking"),
                    ("construction", "Construction"),
                    ("consulting", "Consulting"),
                    ("education", "Education"),
                    ("electronics", "Electronics"),
                    ("energy", "Energy"),
                    ("finance", "Finance"),
                    ("healthcare", "Healthcare"),
                    ("hospitality", "Hospitality"),
                    ("insurance", "Insurance"),
                    ("manufacturing", "Manufacturing"),
                    ("media", "Media"),
                    ("nonprofit", "Non-profit"),
                    ("real_estate", "Real Estate"),
                    ("retail", "Retail"),
                    ("technology", "Technology"),
                    ("telecommunications", "Telecommunications"),
                    ("transportation", "Transportation"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
