# Generated by Django 4.2.23 on 2025-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_opportunity_type_alter_account_industry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted",
            field=models.BooleanField(default=False),
        ),
    ]
