# Generated by Django 4.2.23 on 2025-06-13 08:16

from django.db import migrations, models


def map_old_statuses_to_new(apps, schema_editor):
    """Map old status/stage values to new ones"""
    Lead = apps.get_model('crm', 'Lead')
    Opportunity = apps.get_model('crm', 'Opportunity')
    
    # Lead status mapping
    lead_mapping = {
        'assigned': 'contacted',
        'in_process': 'in_qualification', 
        'converted': 'converted_to_opportunity',
        'recycled': 'disqualified',
        'dead': 'disqualified',
        # 'new' stays the same
    }
    
    for old_status, new_status in lead_mapping.items():
        Lead.objects.filter(status=old_status).update(status=new_status)
    
    # Opportunity stage mapping
    opportunity_mapping = {
        'needs_analysis': 'qualification',
        'value_proposition': 'qualification',
        'id_decision_makers': 'qualification',
        'perception_analysis': 'qualification',
        'proposal_price_quote': 'proposal',
        'negotiation_review': 'negotiation',
        # 'prospecting', 'qualification', 'closed_won', 'closed_lost' stay the same
    }
    
    for old_stage, new_stage in opportunity_mapping.items():
        Opportunity.objects.filter(stage=old_stage).update(stage=new_stage)


def reverse_mapping(apps, schema_editor):
    """Reverse mapping for rollback"""
    Lead = apps.get_model('crm', 'Lead')
    Opportunity = apps.get_model('crm', 'Opportunity')
    
    # Reverse lead mapping (best effort)
    Lead.objects.filter(status='contacted').update(status='assigned')
    Lead.objects.filter(status='in_qualification').update(status='in_process')
    Lead.objects.filter(status='converted_to_opportunity').update(status='converted')
    Lead.objects.filter(status='disqualified').update(status='dead')
    
    # Reverse opportunity mapping (best effort)
    Opportunity.objects.filter(stage='proposal').update(stage='proposal_price_quote')
    Opportunity.objects.filter(stage='negotiation').update(stage='negotiation_review')


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_add_lead_converted_field"),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(map_old_statuses_to_new, reverse_mapping),
        
        # Then update the field definitions
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("in_qualification", "In Qualification"),
                    ("disqualified", "Disqualified"),
                    ("converted_to_opportunity", "Converted to Opportunity"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("prospecting", "Prospecting"),
                    ("qualification", "Qualification"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("closed_won", "Closed - Won"),
                    ("closed_lost", "Closed - Lost"),
                ],
                default="prospecting",
                max_length=50,
            ),
        ),
    ]
