# Generated by Django 4.2.23 on 2025-06-13 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_role_deleted_role_deleted_at_team_deleted_and_more"),
        ("crm", "0006_update_workflow_stages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("email_address_is_opted_out", models.BooleanField(default=False)),
                ("email_address_is_invalid", models.BooleanField(default=False)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("phone_number_is_opted_out", models.BooleanField(default=False)),
                ("phone_number_is_invalid", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("company_name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "ico",
                    models.CharField(
                        blank=True, help_text="Czech business ID", max_length=20
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_first_name", models.CharField(blank=True, max_length=100)),
                ("contact_last_name", models.CharField(blank=True, max_length=100)),
                ("contact_title", models.CharField(blank=True, max_length=100)),
                (
                    "additional_contacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional contact info from business registry",
                    ),
                ),
                (
                    "niche",
                    models.CharField(
                        help_text="Target market/industry keyword", max_length=100
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Geographic search location", max_length=100
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True, help_text="Original search keyword", max_length=100
                    ),
                ),
                (
                    "campaign_id",
                    models.CharField(
                        blank=True, help_text="Campaign identifier", max_length=100
                    ),
                ),
                ("address_street", models.CharField(blank=True, max_length=255)),
                ("address_city", models.CharField(blank=True, max_length=100)),
                ("address_state", models.CharField(blank=True, max_length=100)),
                ("address_country", models.CharField(blank=True, max_length=100)),
                ("address_postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("validated", "Validated"),
                            ("email_generated", "Email Generated"),
                            ("sent", "Sent"),
                            ("follow_up_1", "Follow-up 1"),
                            ("follow_up_2", "Follow-up 2"),
                            ("follow_up_3", "Follow-up 3"),
                            ("responded", "Responded"),
                            ("converted", "Converted"),
                            ("dead", "Dead"),
                            ("disqualified", "Disqualified"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "sequence_position",
                    models.IntegerField(
                        choices=[
                            (0, "Initial Email"),
                            (1, "Follow-up 1"),
                            (2, "Follow-up 2"),
                            (3, "Follow-up 3"),
                            (4, "Completed"),
                        ],
                        default=0,
                    ),
                ),
                ("next_followup_date", models.DateTimeField(blank=True, null=True)),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_status", models.CharField(blank=True, max_length=50)),
                ("validated", models.BooleanField(default=False)),
                ("validation_notes", models.TextField(blank=True)),
                (
                    "auto_validation_score",
                    models.FloatField(
                        blank=True, help_text="AI-generated quality score", null=True
                    ),
                ),
                ("last_email_sent", models.DateTimeField(blank=True, null=True)),
                ("response_received", models.BooleanField(default=False)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("converted_to_lead", models.BooleanField(default=False)),
                ("converted_to_contact", models.BooleanField(default=False)),
                ("converted_to_organization", models.BooleanField(default=False)),
                ("lead_id", models.UUIDField(blank=True, null=True)),
                ("contact_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "assigned_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_assigned",
                        to="users.team",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "db_table": "prospects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="prospects_status_a22ccb_idx"),
                    models.Index(
                        fields=["niche", "location"], name="prospects_niche_8f4f2b_idx"
                    ),
                    models.Index(
                        fields=["next_followup_date"],
                        name="prospects_next_fo_a530f5_idx",
                    ),
                    models.Index(
                        fields=["campaign_id"], name="prospects_campaig_d7b1c7_idx"
                    ),
                    models.Index(
                        fields=["validated"], name="prospects_validat_6b9ee4_idx"
                    ),
                ],
            },
        ),
    ]
