# Generated by Django 4.2.23 on 2025-06-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_prospect"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="business_activities",
            field=models.JSONField(
                blank=True, default=list, help_text="NACE codes and descriptions"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="employee_count_range",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="prospect",
            name="ico_enriched",
            field=models.BooleanField(
                default=False, help_text="Data enriched from Czech ARES registry"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="ico_enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="legal_form",
            field=models.CharField(
                blank=True, help_text="Legal form from ARES", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="legal_form_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="prospect",
            name="registration_date",
            field=models.DateField(
                blank=True, help_text="Company registration date", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(fields=["ico"], name="prospects_ico_b55f1b_idx"),
        ),
        migrations.AddIndex(
            model_name="prospect",
            index=models.Index(
                fields=["ico_enriched"], name="prospects_ico_enr_880c00_idx"
            ),
        ),
    ]
