# Generated by Django 4.2.23 on 2025-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_add_ico_enrichment_to_models"),
    ]

    operations = [
        # Raw SQL to add missing columns if they don't exist
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN 
                -- Add ICO fields to accounts table if they don't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='ico') THEN
                    ALTER TABLE accounts ADD COLUMN ico VARCHAR(20) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='ico_enriched') THEN
                    ALTER TABLE accounts ADD COLUMN ico_enriched BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='ico_enriched_at') THEN
                    ALTER TABLE accounts ADD COLUMN ico_enriched_at TIMESTAMP WITH TIME ZONE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='legal_form') THEN
                    ALTER TABLE accounts ADD COLUMN legal_form VARCHAR(100) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='legal_form_code') THEN
                    ALTER TABLE accounts ADD COLUMN legal_form_code VARCHAR(10) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='registration_date') THEN
                    ALTER TABLE accounts ADD COLUMN registration_date DATE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accounts' AND column_name='business_activities') THEN
                    ALTER TABLE accounts ADD COLUMN business_activities JSONB DEFAULT '[]'::jsonb NOT NULL;
                END IF;
                
                -- Add ICO fields to leads table if they don't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='ico') THEN
                    ALTER TABLE leads ADD COLUMN ico VARCHAR(20) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='ico_enriched') THEN
                    ALTER TABLE leads ADD COLUMN ico_enriched BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='ico_enriched_at') THEN
                    ALTER TABLE leads ADD COLUMN ico_enriched_at TIMESTAMP WITH TIME ZONE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='legal_form') THEN
                    ALTER TABLE leads ADD COLUMN legal_form VARCHAR(100) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='legal_form_code') THEN
                    ALTER TABLE leads ADD COLUMN legal_form_code VARCHAR(10) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='registration_date') THEN
                    ALTER TABLE leads ADD COLUMN registration_date DATE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='leads' AND column_name='business_activities') THEN
                    ALTER TABLE leads ADD COLUMN business_activities JSONB DEFAULT '[]'::jsonb NOT NULL;
                END IF;
                
                -- Add ICO fields to opportunities table if they don't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='opportunities' AND column_name='ico') THEN
                    ALTER TABLE opportunities ADD COLUMN ico VARCHAR(20) DEFAULT '' NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='opportunities' AND column_name='ico_enriched') THEN
                    ALTER TABLE opportunities ADD COLUMN ico_enriched BOOLEAN DEFAULT FALSE NOT NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='opportunities' AND column_name='ico_enriched_at') THEN
                    ALTER TABLE opportunities ADD COLUMN ico_enriched_at TIMESTAMP WITH TIME ZONE;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE accounts DROP COLUMN IF EXISTS ico;
            ALTER TABLE accounts DROP COLUMN IF EXISTS ico_enriched;
            ALTER TABLE accounts DROP COLUMN IF EXISTS ico_enriched_at;
            ALTER TABLE accounts DROP COLUMN IF EXISTS legal_form;
            ALTER TABLE accounts DROP COLUMN IF EXISTS legal_form_code;
            ALTER TABLE accounts DROP COLUMN IF EXISTS registration_date;
            ALTER TABLE accounts DROP COLUMN IF EXISTS business_activities;
            ALTER TABLE leads DROP COLUMN IF EXISTS ico;
            ALTER TABLE leads DROP COLUMN IF EXISTS ico_enriched;
            ALTER TABLE leads DROP COLUMN IF EXISTS ico_enriched_at;
            ALTER TABLE leads DROP COLUMN IF EXISTS legal_form;
            ALTER TABLE leads DROP COLUMN IF EXISTS legal_form_code;
            ALTER TABLE leads DROP COLUMN IF EXISTS registration_date;
            ALTER TABLE leads DROP COLUMN IF EXISTS business_activities;
            ALTER TABLE opportunities DROP COLUMN IF EXISTS ico;
            ALTER TABLE opportunities DROP COLUMN IF EXISTS ico_enriched;
            ALTER TABLE opportunities DROP COLUMN IF EXISTS ico_enriched_at;
            """
        ),
    ]
