# Generated by Django 4.2.23 on 2025-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_add_missing_ico_fields"),
    ]

    operations = [
        # Add ICO fields to Account model
        migrations.AddField(
            model_name='account',
            name='ico',
            field=models.CharField(max_length=20, blank=True, default='', help_text="Czech business ID"),
        ),
        migrations.AddField(
            model_name='account',
            name='ico_enriched',
            field=models.BooleanField(default=False, help_text="Data enriched from Czech ARES registry"),
        ),
        migrations.AddField(
            model_name='account',
            name='ico_enriched_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='legal_form',
            field=models.CharField(max_length=100, blank=True, default='', help_text="Legal form from ARES"),
        ),
        migrations.AddField(
            model_name='account',
            name='legal_form_code',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='registration_date',
            field=models.DateField(null=True, blank=True, help_text="Company registration date"),
        ),
        migrations.AddField(
            model_name='account',
            name='business_activities',
            field=models.JSONField(default=list, blank=True, help_text="NACE codes and descriptions"),
        ),
        
        # Add ICO fields to Lead model
        migrations.AddField(
            model_name='lead',
            name='ico',
            field=models.CharField(max_length=20, blank=True, default='', help_text="Czech business ID"),
        ),
        migrations.AddField(
            model_name='lead',
            name='ico_enriched',
            field=models.BooleanField(default=False, help_text="Data enriched from Czech ARES registry"),
        ),
        migrations.AddField(
            model_name='lead',
            name='ico_enriched_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='legal_form',
            field=models.CharField(max_length=100, blank=True, default='', help_text="Legal form from ARES"),
        ),
        migrations.AddField(
            model_name='lead',
            name='legal_form_code',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='registration_date',
            field=models.DateField(null=True, blank=True, help_text="Company registration date"),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_activities',
            field=models.JSONField(default=list, blank=True, help_text="NACE codes and descriptions"),
        ),
        
        # Add ICO fields to Opportunity model
        migrations.AddField(
            model_name='opportunity',
            name='ico',
            field=models.CharField(max_length=20, blank=True, default='', help_text="Czech business ID"),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='ico_enriched',
            field=models.BooleanField(default=False, help_text="Data enriched from Czech ARES registry"),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='ico_enriched_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]